version: "3.8"
services:
  db_service:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017  
    volumes:
      - db:/data/db
  app:
    depends_on:
      - db_service
    build: ./nodejs-express-mongodb
    restart: unless-stopped
    ports:
      - 8080
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=database
      - DB_PORT=27017
    stdin_open: true
    tty: true
volumes:
  db: